app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :theories
  resources :assumptions
  resources :practices

  root 'map#index'

  # User Login
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/user/info' => 'user#show'
  if Rails.env.test?
    get 'test', to: 'test#index'
    namespace :test do
      resource :session, only: %i[create]
    end
  end

  # Concept Map
  get '/init' => 'main#index'
  get '/api/v1/map' => 'map#all'

  match '*path', to: redirect('/'), via: :all
end

app/app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  def index; end
end

app/app/views/main/index.html.erb
<html lang="en">
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'bootstrap-icons', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'boxicons', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <title>Home</title>
</head>

<body style="background: white; height: 100vh">
<p style="color: green"><%= notice %></p>

<% if flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="flex-wrapper">
  <div class="list-group list-group-light">
    <%= link_to theories_path, id: "theories",
                class: "engraved list-group-item list-group-item-action px-3 border-0 ripple link" do %>
      <span>Theories</span>
    <% end %>
    <%= link_to assumptions_path, id: "assumptions",
                class: "engraved list-group-item list-group-item-action px-3 border-0 ripple link" do %>
      <span>Assumptions</span>
    <% end %>
    <%= link_to practices_path, id: "apractices",
                class: "engraved list-group-item list-group-item-action px-3 border-0 ripple link" do %>
      <span>Practices</span>
    <% end %>
  </div>

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright" style="padding: 20px">
      &copy; IDEALS The utilization of this online tool is based on its central, bifold goal of providing theoretical support to
      teaching practices and of offering practical approaches to apply learning theories.
    </div>
  </footer><!-- End Footer -->
</div>

</body>
</html>