app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :theories
  resources :assumptions
  resources :practices

  root 'map#index'

  # User Login
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/user/info' => 'user#show'
  if Rails.env.test?
    get 'test', to: 'test#index'
    namespace :test do
      resource :session, only: %i[create]
    end
  end

  # Concept Map
  get '/init' => 'main#index'
  get '/api/v1/map' => 'map#all'

  match '*path', to: redirect('/'), via: :all
end

app/app/models/assumption.rb
# frozen_string_literal: true

class Assumption < ApplicationRecord
  has_and_belongs_to_many :theories
  has_and_belongs_to_many :practices
  has_rich_text :description
  validates :name, presence: true
end

app/app/controllers/assumptions_controller.rb
# frozen_string_literal: true

class AssumptionsController < ApplicationController
  before_action :set_assumption, only: %i[show edit update destroy]
  before_action :require_login, only: %i[new create edit update destroy]
  # GET /assumptions or /assumptions.json
  def index
    @assumptions = Assumption.paginate(page: params[:page], per_page: 12)
  end

  # GET /assumptions/1 or /assumptions/1.json
  def show; end

  # GET /assumptions/new
  def new
    @assumption = Assumption.new
  end

  # GET /assumptions/1/edit
  def edit; end

  # POST /assumptions or /assumptions.json
  def create
    @assumption = Assumption.new(assumption_params)

    respond_to do |format|
      if @assumption.save
        format.html { redirect_to assumption_url(@assumption), notice: 'Assumption was successfully created.' }
        format.json { render :show, status: :created, location: @assumption }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assumptions/1 or /assumptions/1.json
  def update
    respond_to do |format|
      # no theory select
      @assumption.theories.clear if params[:assumption][:theory_ids].nil?

      # no practice select
      @assumption.practices.clear if params[:assumption][:practice_ids].nil?

      if @assumption.update(assumption_params)
        format.html { redirect_to assumption_url(@assumption), notice: 'Assumption was successfully updated.' }
        format.json { render :show, status: :ok, location: @assumption }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assumptions/1 or /assumptions/1.json
  def destroy
    @assumption.destroy

    respond_to do |format|
      format.html { redirect_to assumptions_url, notice: 'Assumption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_assumption
    @assumption = Assumption.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def assumption_params
    params.require(:assumption).permit(:name, :description, theory_ids: [], practice_ids: [])
  end
end

app/app/helpers/assumptions_helper.rb
# frozen_string_literal: true

module AssumptionsHelper
end

app/app/views/assumptions/_assumption.html.erb
<div id="<%= dom_id assumption %>">

  <div class="engraved">
    <span><%= assumption.name.capitalize %></span>
  </div>

  <p>
    <strong>Description:</strong>
    <% doc = Nokogiri::HTML.fragment(assumption.description.to_s) %>
    <% doc.css('a').each do |link| %>
      <% link.set_attribute('target', '_blank') %>
      <% link.set_attribute('rel', 'noopener noreferrer') %>
    <% end %>
    <%= doc.to_html.html_safe %>
    <%= "No description provided" if assumption.description.empty? %>
  </p>

  <% assumption.theories.each do |theory| %>
    <p>
      <strong>Theory:</strong>
      <%= theory.name.capitalize %><br>
      <%= link_to "show this theory", theory_path(theory.id) %>
    </p>
  <% end %>

  <% assumption.practices.each do |practice| %>
    <p>
      <strong>Practice:</strong>
      <%= practice.name.capitalize %><br>
      <%= link_to "show this practice", practice_path(practice.id) %>
    </p>
  <% end %>
</div>

app/app/views/assumptions/_form.html.erb
<%= javascript_pack_tag "application" %>
<%= form_with(model: assumption) do |form| %>
  <% if assumption.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assumption.errors.count, "error") %> prohibited this assumption from being saved:</h2>

      <ul>
        <% assumption.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <br>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <br>

  <div class="field form-group">
    <%= form.label :theory_ids, "Select Theory" %>
    <% Theory.all.each do |theory| %>
      <div class="form-check">
        <%= check_box_tag "assumption[theory_ids][]", theory.id, @assumption.theories.include?(theory),
                          id: "theory_#{theory.id}", class: 'form-check-input' %>
        <%= label_tag "theory_#{theory.id}", theory.name, for: "theory_#{theory.id}", class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <br>

  <div class="field form-group">
    <%= form.label :practice_ids, "Select Practice" %>
    <% Practice.all.each do |practice| %>
      <div class="form-check">
        <%= check_box_tag "assumption[practice_ids][]", practice.id, @assumption.practices.include?(practice),
                          id: "practice_#{practice.id}", class: 'form-check-input' %>
        <%= label_tag "practice_#{practice.id}", practice.name, for: "practice_#{practice.id}", class: 'form-check-label' %>
      </div>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.submit class: "btn btn-outline-primary"%>
  </div>
<% end %>

app/app/views/assumptions/edit.html.erb
<div style="padding-left: 20px; padding-right: 10px; padding-top: 15px">

  <div class="title-container" style="display: flex; align-items: center;">
    <%= link_to assumptions_path, class: "icon-link", style: "font-size: 20px; position: relative; padding-right: 5px; padding-top: 2px", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Back", onclick: "return confirmNavigation();" do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>

    <div class="engraved">
      <span>Edit Assumption</span>
    </div>
  </div>

  <%= render "form", assumption: @assumption %>

  <br>

  <div>
    <%= link_to "Show this assumption", @assumption %>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        const tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });

    function confirmNavigation() {
        return confirm('Do you want to go back?');
    }
</script>

app/app/views/assumptions/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex-wrapper">

  <div class="title-container" style="display: flex; align-items: center; justify-content: space-between; padding-left: 20px">
    <div class="engraved">
      <span>Assumptions</span>
    </div>

    <% if session[:userinfo].present? %>
      <%= link_to new_assumption_path, class: "icon-link", style: "padding-right: 20px; font-size: 24px; position: relative; top: 5px;" do %>
        <i class="bi bi-plus-square"></i>
      <% end %>
    <% end %>
  </div>

  <div class="list-group list-group-light">
    <% @assumptions.each do |assumption| %>
      <%= link_to assumption,
                  class: "list-group-item list-group-item-action px-3 border-0 ripple link" do %>
        <i class="bi bi-arrow-right-circle-fill"></i> <%= assumption.name.capitalize %>
      <% end %>
    <% end %>
  </div>
 
  <!-- if in the cucumber test, show the button -->
  <% if Rails.env.test? %>
    <p><%= link_to "New assumption", new_assumption_path %></p>
  <% end %>
  <div style="height:64px;"></div>
  <div class="d-flex justify-content-center fixed-bottom">
    <nav aria-label="Page navigation">
      <ul class="pagination">
        <% if @assumptions.previous_page %>
          <li class="page-item"><%= link_to 'Prev', assumptions_path(page: @assumptions.previous_page), class: 'page-link' %></li>
        <% else %>
          <li class="page-item disabled"><span class="page-link">Prev</span></li>
        <% end %>

        <% if @assumptions.total_pages >= 1 %>
          <% current_page = @assumptions.current_page %>

          <% if current_page == 1 %>
            <li class="page-item active"><span class="page-link"><%= current_page %></span></li>
          <% elsif current_page == @assumptions.total_pages %>
            <li class="page-item active"><span class="page-link"><%= current_page %></span></li>
          <% else %>
            <li class="page-item active"><span class="page-link"><%= current_page %></span></li>
          <% end %>
        <% end %>

        <% if @assumptions.next_page %>
          <li class="page-item"><%= link_to 'Next', assumptions_path(page: @assumptions.next_page), class: 'page-link' %></li>
        <% else %>
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        <% end %>
      </ul>
    </nav>
  </div>

</div>

app/app/views/assumptions/new.html.erb
<div style="padding-left: 20px; padding-right: 10px; padding-top: 15px">

  <div class="title-container" style="display: flex; align-items: center;">
    <%= link_to assumptions_path, class: "icon-link", style: "font-size: 20px; position: relative; padding-right: 5px; padding-top: 2px", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Back", onclick: "return confirmNavigation();" do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>

    <div class="engraved">
      <span>New Assumption</span>
    </div>
  </div>

  <%= render "form", assumption: @assumption %>

  <br>

</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });

    function confirmNavigation() {
        return confirm('Do you want to go back?');
    }
</script>

app/app/views/assumptions/show.html.erb
<div style="padding-left: 20px; padding-right: 10px">

  <p style="color: green"><%= notice %></p>

  <%= render @assumption %>

  <div>

    <%= link_to "Back", assumptions_path %>
    <!-- if in the cucumber test, show the button -->
    <% if Rails.env.test? %>
      | <%= link_to "Edit this assumption", edit_assumption_path(@assumption) %>
      <%= button_to "Destroy this assumption", @assumption, method: :delete %>
    <% end %>

    <!-- if in the production, show the button -->
    <% if session[:userinfo].present? %>
      | <%= link_to "Edit", edit_assumption_path(@assumption) %>
      <%= button_to "Delete", @assumption, method: :delete, class: "btn btn-outline-danger" %>
    <% end %>
  </div>
</div>
<script>
    const assumption = <%= @assumption.to_json.html_safe %>;
    document.addEventListener('DOMContentLoaded', () => {
        const label = 'assumptions' + assumption.id;
        window.parent.initGraph(true, label);
    });
</script>