app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :theories
  resources :assumptions
  resources :practices

  root 'map#index'

  # User Login
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/user/info' => 'user#show'
  if Rails.env.test?
    get 'test', to: 'test#index'
    namespace :test do
      resource :session, only: %i[create]
    end
  end

  # Concept Map
  get '/init' => 'main#index'
  get '/api/v1/map' => 'map#all'

  match '*path', to: redirect('/'), via: :all
end

app/app/models/practice.rb
# frozen_string_literal: true

class Practice < ApplicationRecord
  has_and_belongs_to_many :assumptions
  has_rich_text :description
  validates :name, presence: true
end

app/app/controllers/practices_controller.rb
# frozen_string_literal: true

class PracticesController < ApplicationController
  before_action :set_practice, only: %i[show edit update destroy]
  before_action :require_login
  skip_before_action :require_login, only: %i[index show]
  # GET /practices or /practices.json
  def index
    @practices = Practice.paginate(page: params[:page], per_page: 12)
  end

  # GET /practices/1 or /practices/1.json
  def show; end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit; end

  # POST /practices or /practices.json
  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to practice_url(@practice), notice: 'Practice was successfully created.' }
        format.json { render :show, status: :created, location: @practice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1 or /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to practice_url(@practice), notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1 or /practices/1.json
  def destroy
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_practice
    @practice = Practice.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def practice_params
    params.require(:practice).permit(:name, :description)
  end
end

app/app/helpers/practices_helper.rb
# frozen_string_literal: true

module PracticesHelper
end

app/app/views/practices/_form.html.erb
<%= javascript_pack_tag "application" %>
<%= form_with(model: practice) do |form| %>
  <% if practice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
        <% practice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="form-group">
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <br>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <br>

  <br>

  <div>
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/app/views/practices/_practice.html.erb
<div id="<%= dom_id practice %>">
  <div class="engraved">
    <span><%= practice.name.capitalize %></span>
  </div>

  <p>
    <strong>Description:</strong>
    <% doc = Nokogiri::HTML.fragment(practice.description.to_s) %>
    <% doc.css('a').each do |link| %>
      <% link.set_attribute('target', '_blank') %>
      <% link.set_attribute('rel', 'noopener noreferrer') %>
    <% end %>
    <%= doc.to_html.html_safe %>

    <%= "No description provided" if practice.description.empty? %>
  </p>

  <% practice.assumptions.each do |assump| %>
    <p>
      <strong>Assumption:</strong>
      <%= assump.name.capitalize %><br>
      <%= link_to "show this assumption", assumption_path(assump.id) %>
    </p>
  <% end %>
</div>

app/app/views/practices/edit.html.erb
<div style="padding-left: 20px; padding-right: 10px; padding-top: 15px">

  <div class="title-container" style="display: flex; align-items: center;">
    <%= link_to practices_path, class: "icon-link", style: "font-size: 20px; position: relative; padding-right: 5px; padding-top: 2px", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Back", onclick: "return confirmNavigation();" do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>

    <div class="engraved">
      <span>Edit Practice</span>
    </div>
  </div>

  <%= render "form", practice: @practice %>

  <br>

  <div>
    <%= link_to "Show this practice", @practice %>
  </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });

    function confirmNavigation() {
        return confirm('Do you want to go back?');
    }
</script>

app/app/views/practices/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex-wrapper">

  <div class="title-container" style="display: flex; align-items: center; justify-content: space-between; padding-left: 20px">
    <div class="engraved">
      <span>Practices</span>
    </div>

    <% if session[:userinfo].present? %>
      <%= link_to new_practice_path, class: "icon-link", style: "padding-right: 20px; font-size: 24px; position: relative; top: 5px;" do %>
        <i class="bi bi-plus-square"></i>
      <% end %>
    <% end %>
  </div>

  <div class="list-group list-group-light">
    <% @practices.each do |practice| %>
      <%= link_to practice,
                  class: "list-group-item list-group-item-action px-3 border-0 ripple link" do %>
        <i class="bi bi-arrow-right-circle-fill"></i> <%= practice.name.capitalize %>
      <% end %>
    <% end %>
  </div>
  <div style="height:64px;"></div>
  <!-- if in the cucumber test, show the button -->
  <% if Rails.env.test? %>
    <p><%= link_to "New practice", new_practice_path %></p>
  <% end %>
  
  <div class="d-flex justify-content-center fixed-bottom">
    <nav aria-label="Page navigation">
      <ul class="pagination">
        <% if @practices.previous_page %>
          <li class="page-item"><%= link_to 'Prev', practices_path(page: @practices.previous_page), class: 'page-link' %></li>
        <% else %>
          <li class="page-item disabled"><span class="page-link">Prev</span></li>
        <% end %>

        <% if @practices.total_pages >= 1 %>
          <% current_page = @practices.current_page %>

          <% if current_page == 1 %>
            <li class="page-item active"><span class="page-link"><%= current_page %></span></li>
          <% elsif current_page == @practices.total_pages %>
            <li class="page-item active"><span class="page-link"><%= current_page %></span></li>
          <% else %>
            <li class="page-item active"><span class="page-link"><%= current_page %></span></li>
          <% end %>
        <% end %>

        <% if @practices.next_page %>
          <li class="page-item"><%= link_to 'Next', practices_path(page: @practices.next_page), class: 'page-link' %></li>
        <% else %>
          <li class="page-item disabled"><span class="page-link">Next</span></li>
        <% end %>
      </ul>
    </nav>
  </div>

</div>

app/app/views/practices/new.html.erb
<div style="padding-left: 20px; padding-right: 10px; padding-top: 15px">

  <div class="title-container" style="display: flex; align-items: center;">
    <%= link_to practices_path, class: "icon-link", style: "font-size: 20px; position: relative; padding-right: 5px; padding-top: 2px", "data-bs-toggle": "tooltip", "data-bs-placement": "top", title: "Back", onclick: "return confirmNavigation();" do %>
      <i class="bi bi-arrow-left"></i>
    <% end %>

    <div class="engraved">
      <span>New Practice</span>
    </div>
  </div>

  <%= render "form", practice: @practice %>

  <br>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl);
        });
    });

    function confirmNavigation() {
        return confirm('Do you want to go back?');
    }
</script>

app/app/views/practices/show.html.erb
<div style="padding-left: 20px; padding-right: 10px">
  <p style="color: green"><%= notice %></p>

  <%= render @practice %>

  <div>

    <%= link_to "Back", practices_path %>
    <!-- if in the cucumber test, show the button -->
    <% if Rails.env.test? %>
      | <%= link_to "Edit this practice", edit_practice_path(@practice) %>
      <%= button_to "Destroy this practice", @practice, method: :delete %>
    <% end %>
    <!-- if in the production, show the button -->
    <% if session[:userinfo].present? %>
      | <%= link_to "Edit", edit_practice_path(@practice) %>
      <%= button_to "Delete", @practice, method: :delete, class: "btn btn-outline-danger" %>
    <% end %>
  </div>
</div>

<script>
    const practice = <%= @practice.to_json.html_safe %>;
    document.addEventListener('DOMContentLoaded', () => {
        const label = 'practices' + practice.id;
        window.parent.initGraph(true, label);
    });
</script>